services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    container_name: yii2-php
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=db
      - DB_DATABASE=yii2db
      - DB_USERNAME=yii2user
      - DB_PASSWORD=secret
  db:
    image: mysql:5.7
    container_name: yii2-db
    ports:
      - "3316:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=yii2db
      - MYSQL_USER=yii2user
      - MYSQL_PASSWORD=secret
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: